apiVersion: monitoring.rhobs/v1alpha1
kind: MonitoringStack
metadata:
 labels:
   eap: eap-monitoring-stack
 name: eap-monitoring-stack
spec:
 alertmanagerConfig:
   disabled: true
 prometheusConfig:
   replicas: 1
 retention: 2d
 resourceSelector:
   matchLabels:
     monitoredby: eap-monitoring-stack
