FROM quay.io/jdenise/jboss-eap8-domain-openjdk21-openshift-centos:latest
COPY --chown=jboss:root extensions $JBOSS_HOME/extensions
RUN chmod a+x $JBOSS_HOME/extensions/postconfigure.sh
#Copy host configuration, due to host name being set in it
COPY --chown=jboss:root my-host.xml $JBOSS_HOME/domain/configuration

podman run --log-level=debug --rm -p 8080:8080 –-env JBOSS_EAP_DOMAIN_HOST_NAME=secondary --env SERVER_ARGS="--host-config=my-host.xml -Djboss.domain.primary.address=host.containers.internal -Djboss.bind.address=0.0.0.0" quay.io/jdenise/my-host-controller:latest
