version: '3.8'

services:
  base-image:
    build:
      context: ./eap8-domain-openjdk21-openshift
      dockerfile: Containerfile
    image: localhost/jboss-eap8-domain-openjdk21-openshift:latest

  domain-controller:
    depends_on:
    - base-image
    build:
      context: ./domain-controller-image          # Path to the directory containing the Dockerfile
      dockerfile: Containerfile     # (Optional) Specify the Dockerfile name, defaults to 'Dockerfile'
    hostname: primary
    ports:
    - "9990:9990"
    environment:
    - JBOSS_EAP_DOMAIN_HOST_NAME=primary
    - JBOSS_EAP_DOMAIN_USER=secondary
    - JBOSS_EAP_DOMAIN_PASSWORD=secondary
    - SERVER_PUBLIC_BIND_ADDRESS=0.0.0.0
    - SERVER_MANAGEMENT_BIND_ADDRESS=0.0.0.0
    labels:
    - "mode=domain-controller"
    restart: always

  secondary-host:
    depends_on:
    - base-image
    build:
      context: ./host-controller-image
      dockerfile: Containerfile
    hostname: secondary
    ports:
    - "8080:8080"
    environment:
    - JBOSS_EAP_DOMAIN_HOST_NAME=secondary
    - JBOSS_EAP_DOMAIN_USER=secondary
    - JBOSS_EAP_DOMAIN_PASSWORD=secondary
    - JBOSS_EAP_DOMAIN_PRIMARY_ADDRESS=primary
    - JBOSS_EAP_DOMAIN_HOST_CONFIG=my-host-secondary.xml
    - SERVER_PUBLIC_BIND_ADDRESS=0.0.0.0
    - SERVER_MANAGEMENT_BIND_ADDRESS=0.0.0.0
    labels:
    - "mode=host-controller"
    restart: always

