kind: Service
apiVersion: v1
metadata:
  name: ha-service
  labels:
    app: eap-demo
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: ha-service-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: prometheus
      protocol: TCP
      port: 9799
      targetPort: 9799
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: hc-ha-openshift

