kind: Pod
apiVersion: v1
metadata:
  name: domain-controller
  labels:
    app: domain-controller
spec:
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  containers:
    - resources:
        limits:
          cpu: '1'
          memory: 1000Mi
        requests:
          cpu: 10m
          memory: 64Mi
      terminationMessagePath: /dev/termination-log
      name: domain-controller-domain-controller-container
      env:
        - name: TERM
          value: xterm
        - name: JBOSS_EAP_DOMAIN_HOST_CONFIG
          value: my-host-primary.xml
        - name: JBOSS_EAP_DOMAIN_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: JBOSS_EAP_DOMAIN_DOMAIN_CONFIG
          value: openshift-domain.xml
        - name: JBOSS_EAP_DOMAIN_USER
          value: demo
        - name: JBOSS_EAP_DOMAIN_PASSWORD
          value: demo
        - name: JBOSS_EAP_DOMAIN_DOMAIN_INIT_PATH
          value: /tmp/domain-init
      ports:
        - containerPort: 9990
          protocol: TCP
      imagePullPolicy: IfNotPresent
      terminationMessagePolicy: File
      image: 'quay.io/jdenise/jboss-eap8-domain-openjdk21-openshift:16.0'
      volumeMounts:
        - mountPath: /tmp/domain-init
          name: dc-init-volume
  volumes:
    - name: dc-init-volume
      persistentVolumeClaim:
        claimName: dc-setup-volume
        