kind: Pod
apiVersion: v1
metadata:
  name: secondary-openshift
  labels:
    app: secondary-openshift
    domain.member: demo
spec:
  restartPolicy: Always
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  containers:
    - resources:
        limits:
          cpu: '1'
          memory: 1000Mi
        requests:
          cpu: 10m
          memory: 64Mi
      terminationMessagePath: /dev/termination-log
      name: secondary-openshift-secondary-host-controller-container
      env:
        - name: JBOSS_EAP_DOMAIN_HOST_CONFIG
          value: my-host.xml
        - name: JBOSS_EAP_DOMAIN_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: JAVA_MAX_MEM_RATIO
          value: "70.0"
        - name: TERM
          value: xterm
        - name: JBOSS_EAP_DOMAIN_PRIMARY_ADDRESS
          value: domain-controller
        - name: JBOSS_EAP_DOMAIN_USER
          value: demo
        - name: JBOSS_EAP_DOMAIN_PASSWORD
          value: demo
        # Env vars to connect to PostgreSQL DB
        - name: POSTGRESQL_DATABASE
          value: todos-db
        - name: POSTGRESQL_USER
          value: todos-db
        - name: POSTGRESQL_PASSWORD
          value: todos-db
        - name: POSTGRESQL_DATASOURCE
          value: ToDos
        - name: POSTGRESQL_SERVICE_HOST
          value: database-server
        - name: POSTGRESQL_SERVICE_PORT
          value: "5432"
      ports:
        - containerPort: 8080
          protocol: TCP
      imagePullPolicy: IfNotPresent
      terminationMessagePolicy: File
      image: 'quay.io/jdenise/openshift-host-controller:demo-2.2'
  