kind: Pod
apiVersion: v1
metadata:
  name: hc-ha2-openshift
  labels:
    app: hc-ha-openshift
    domain.member: demo
spec:
  restartPolicy: Always
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  containers:
    - resources:
        limits:
          cpu: '1'
          memory: 1000Mi
        requests:
          cpu: 10m
          memory: 64Mi
      terminationMessagePath: /dev/termination-log
      name: ternary-host-controller-container
      env:
        - name: JBOSS_EAP_DOMAIN_HOST_CONFIG
          value: my-host-ha.xml
        - name: JBOSS_EAP_DOMAIN_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: TERM
          value: xterm
        - name: KUBERNETES_NAMESPACE
          value: jdenise-dev
        - name: OPENSHIFT_DNS_PING_SERVICE_NAME
          value: ping-service
        - name: JBOSS_EAP_DOMAIN_PRIMARY_ADDRESS
          value: domain-controller
        - name: JBOSS_EAP_DOMAIN_USER
          value: demo
        - name: JBOSS_EAP_DOMAIN_PASSWORD
          value: demo
        - name: JBOSS_EAP_DOMAIN_DOMAIN_INIT_PATH
          value: /tmp/domain-init
      ports:
        - containerPort: 8080
          protocol: TCP
      imagePullPolicy: IfNotPresent
      terminationMessagePolicy: File
      image: 'quay.io/jdenise/jboss-eap8-domain-openjdk21-openshift:7.0'
      volumeMounts:
        - mountPath: /tmp/domain-init
          name: hc-init-secret
  volumes:
    - name: hc-init-secret
      secret:
        secretName: hc-setup
  