kind: Pod
apiVersion: v1
metadata:
  name: hc-ha1-openshift
  labels:
    app: hc-ha1-openshift
    domain.member: demo
spec:
  restartPolicy: Always
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  containers:
    - resources:
        limits:
          cpu: '1'
          memory: 1000Mi
        requests:
          cpu: 10m
          memory: 64Mi
      terminationMessagePath: /dev/termination-log
      name: ternary-host-controller-container
      env:
        - name: JBOSS_EAP_DOMAIN_HOST_CONFIG
          value: my-host-ha.xml
        - name: JBOSS_EAP_DOMAIN_HOST_NAME
          value: hc-ha1-openshift
        - name: TERM
          value: xterm
        - name: KUBERNETES_NAMESPACE
          value: jdenise-dev
        - name: OPENSHIFT_DNS_PING_SERVICE_NAME
          value: ping-service
        - name: JBOSS_EAP_DOMAIN_PRIMARY_ADDRESS
          value: domain-controller
        - name: JBOSS_EAP_DOMAIN_USER
          value: demo
        - name: JBOSS_EAP_DOMAIN_PASSWORD
          value: demo
      ports:
        - containerPort: 8080
          protocol: TCP
      imagePullPolicy: IfNotPresent
      terminationMessagePolicy: File
      image: 'quay.io/jdenise/openshift-host-controller:demo-2.2'
  