FROM registry.redhat.io/jboss-eap-8/eap8-openjdk17-builder-openshift-rhel8:latest AS builder

# Set up environment variables for provisioning.
ENV GALLEON_PROVISION_CHANNELS org.jboss.eap.channels:eap-8.0
ENV GALLEON_USE_LOCAL_FILE true

# Workaround https://issues.redhat.com/browse/JBEAP-27755
ENV PROVISIONING_MAVEN_PLUGIN_VERSION 1.0.1.Final-redhat-00008

RUN mkdir -p /tmp/src
COPY --chown=jboss:root galleon /tmp/src/galleon

# Run the assemble script to provision the server.
RUN /usr/local/s2i/assemble

# Copy the JBoss EAP 8 server from the builder image to the runtime image.
FROM registry.redhat.io/jboss-eap-8/eap8-openjdk17-runtime-openshift-rhel8:latest AS runtime

# Set appropriate ownership and permissions.
COPY --from=builder --chown=jboss:root $JBOSS_HOME $JBOSS_HOME
# Copy the domain launcher
COPY --chown=jboss:root run-domain.sh $JBOSS_HOME/bin
RUN chmod a+x $JBOSS_HOME/bin/run-domain.sh

# Copy custom modules
COPY --chown=jboss:root modules $JBOSS_HOME/modules
# Copy configurations
COPY --chown=jboss:root configurations/*.xml $JBOSS_HOME/domain/configuration
# Copy init entry-point

COPY --chown=jboss:root init-hook $JBOSS_HOME
COPY --chown=jboss:root admin/* $JBOSS_HOME/bin/launch

# Ensure appropriate permissions for the copied files.
RUN chmod -R ug+rwX $JBOSS_HOME

# install packages required to rsync the deployments
USER root
RUN microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y rsync \
            && microdnf clean all \
            && rpm -q rsync
RUN microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y tar \
            && microdnf clean all \
            && rpm -q tar

ENV JBOSS_CONTAINER_PROMETHEUS_MODULE /opt/jboss/container/prometheus

COPY --chown=jboss:root prometheus/ /

RUN microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y prometheus-jmx-exporter-openjdk17 \
            && microdnf clean all \
            && rpm -q prometheus-jmx-exporter-openjdk17

COPY --chown=jboss:root http-probes/ $JBOSS_HOME/bin/launch
RUN chmod -R ug+rwX $JBOSS_HOME

USER jboss
CMD ["sh", "-c", "${JBOSS_HOME}/bin/run-domain.sh"]

