FROM registry.redhat.io/jboss-eap-8/eap8-openjdk17-builder-openshift-rhel8:latest AS builder

# Set up environment variables for provisioning.
ENV GALLEON_PROVISION_CHANNELS org.jboss.eap.channels:eap-8.0
ENV GALLEON_USE_LOCAL_FILE true
RUN mkdir -p /tmp/src
COPY --chown=jboss:root galleon /tmp/src/galleon

# Run the assemble script to provision the server.
RUN /usr/local/s2i/assemble

# Copy the JBoss EAP 8 server from the builder image to the runtime image.
FROM registry.redhat.io/jboss-eap-8/eap8-openjdk17-runtime-openshift-rhel8:latest AS runtime

# Set appropriate ownership and permissions.
COPY --from=builder --chown=jboss:root $JBOSS_HOME $JBOSS_HOME
# Copy the domain launcher
COPY --chown=jboss:root run-domain.sh $JBOSS_HOME/bin
RUN chmod a+x $JBOSS_HOME/bin/run-domain.sh

# Copy custom modules
COPY --chown=jboss:root modules $JBOSS_HOME/modules
# Copy configurations
COPY --chown=jboss:root configurations/*.xml $JBOSS_HOME/domain/configuration
# Ensure appropriate permissions for the copied files.
RUN chmod -R ug+rwX $JBOSS_HOME

CMD ["sh", "-c", "${JBOSS_HOME}/bin/run-domain.sh"]

